services:
  redis:
    image: 'redis:6'
    restart: unless-stopped
    networks:
      - app

  nginx:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-metrics.rule=Host(`${COMPOSE_SERVER_DOMAIN}`) && PathPrefix(`/metrics`) "
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-metrics.middlewares=ITKMetricsAuth@file"
