services:
  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'

  mail:
    environment:
      - MP_MAX_MESSAGES=10000

  nginx:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-metrics.rule=Host(`${COMPOSE_DOMAIN}`) && PathPrefix(`/metrics`) "
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-metrics.middlewares=ITKMetricsAuth@file"
    volumes:
      - ./iot_alert_manager:/app

  phpfpm:
    volumes:
      - ./iot_alert_manager:/app

  mariadb:
    deploy:
      replicas: 0
